version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: telegram_music
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      APP_PORT: 3000
      DATABASE_URL: postgres://postgres:postgres@postgres:5430/telegram_music?sslmode=disable
    depends_on:
      - postgres

volumes:
  pgdata:
