version: "3.8"

services:
  app:
    build:
      context:  .
      dockerfile: ./deployments/miniapp/Dockerfile

    deploy:
      resources:
        limits:
          cpus: "0.75"      
          memory: 1g        
    ports:
      - "4000:3000"
    environment:
      BOT_ID: 7345427057
      APP_PORT: 3000
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/telegram_music?sslmode=disable
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: telegram_music
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    

volumes:
  pgdata:
