name: CI/CD Pipeline

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: ghcr.io/alex123321-maker/telegram-music-back:latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -f deployments/miniapp/Dockerfile -t $IMAGE_NAME .

      - name: Push Docker image to GHCR
        run: docker push $IMAGE_NAME

      - name: Upload docker-compose to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH }}
          source: "deployments/docker-compose.yml"
          target: "~/telegram-music/miniapp/back"

      - name: SSH & Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH }}
          script: |
            cd ~/telegram-music/miniapp/back/deployments
            docker login ghcr.io -u ${{ github.actor }} --password ${{ secrets.GHCR_TOKEN }}
            docker compose down

            docker compose pull
            docker compose up -d
